In [94]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.metrics import f1_score, accuracy_score, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline

In [41]:
df = pd.read_csv('../data/googleplaystore .csv')

In [42]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [43]:
df.iloc[10472]

App               Life Made WI-Fi Touchscreen Photo Frame
Category                                              1.9
Rating                                               19.0
Reviews                                              3.0M
Size                                               1,000+
Installs                                             Free
Type                                                    0
Price                                                 0.0
Content Rating                                        NaN
Genres                                  February 11, 2018
Last Updated                                       1.0.19
Current Ver                                    4.0 and up
Android Ver                                           NaN
Name: 10472, dtype: object

In [44]:
df = df.drop(index=10472)

In [45]:
df.shape

(10840, 13)

In [46]:
df.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  str
 4   Size            10840 non-null  str
 5   Installs        10840 non-null  str
 6   Type            10839 non-null  str
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(2), str(11)
memory usage: 1.2 MB

In [47]:
df.shape

(10840, 13)

## Нули в:
- `Rating`: float64
- `Type`: str
- `Content Rating`: str
- `Current Ver`: str
- `Android Ver`: str

In [48]:
print(f'Медиана `Rating` - {df['Rating'].median()}')
print(f'Среднее `Rating` - {df['Rating'].mean()}')

Медиана `Rating` - 4.3
Среднее `Rating` - 4.191757420456972

In [49]:
df['Rating'] = df['Rating'].fillna(df['Rating'].median())

In [50]:
df.describe(include='string')

,App,Category,Reviews,Size,Installs,Type,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10840,10840,10840,10840,10840,10839,10840,10840,10840,10832,10838
unique,9659,33,6001,461,21,2,6,119,1377,2831,33
top,ROBLOX,FAMILY,0,Varies with device,"1,000,000+",Free,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,596,1695,1579,10039,8714,842,326,1459,2451

In [51]:
df['Type'] = df['Type'].fillna('Free')
df['Content Rating'] = df['Content Rating'].fillna('Everyone')
df['Current Ver'] = df['Current Ver'].fillna('Varies with device')
df['Android Ver'] = df['Android Ver'].fillna('4.1 and up')

In [52]:
df.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          10840 non-null  float64
 3   Reviews         10840 non-null  str
 4   Size            10840 non-null  str
 5   Installs        10840 non-null  str
 6   Type            10840 non-null  str
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10840 non-null  str
 12  Android Ver     10840 non-null  str
dtypes: float64(2), str(11)
memory usage: 1.2 MB

In [53]:
df.duplicated().sum()

np.int64(483)

In [54]:
df = df.drop_duplicates()

In [55]:
df.shape

(10357, 13)

In [56]:
df['Reviews'] = df['Reviews'].astype(float)

In [57]:
df.info()

<class 'pandas.DataFrame'>
Index: 10357 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10357 non-null  str
 1   Category        10357 non-null  str
 2   Rating          10357 non-null  float64
 3   Reviews         10357 non-null  float64
 4   Size            10357 non-null  str
 5   Installs        10357 non-null  str
 6   Type            10357 non-null  str
 7   Price           10357 non-null  float64
 8   Content Rating  10357 non-null  str
 9   Genres          10357 non-null  str
 10  Last Updated    10357 non-null  str
 11  Current Ver     10357 non-null  str
 12  Android Ver     10357 non-null  str
dtypes: float64(3), str(10)
memory usage: 1.1 MB

In [58]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,"10,000+",Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14M,"500,000+",Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7M,"5,000,000+",Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25M,"50,000,000+",Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8M,"100,000+",Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [59]:
df['Last Updated'] = pd.to_datetime(df['Last Updated'])

In [60]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,"10,000+",Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14M,"500,000+",Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7M,"5,000,000+",Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25M,"50,000,000+",Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8M,"100,000+",Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up

In [61]:
df.info()

<class 'pandas.DataFrame'>
Index: 10357 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10357 non-null  str
 1   Category        10357 non-null  str
 2   Rating          10357 non-null  float64
 3   Reviews         10357 non-null  float64
 4   Size            10357 non-null  str
 5   Installs        10357 non-null  str
 6   Type            10357 non-null  str
 7   Price           10357 non-null  float64
 8   Content Rating  10357 non-null  str
 9   Genres          10357 non-null  str
 10  Last Updated    10357 non-null  datetime64[us]
 11  Current Ver     10357 non-null  str
 12  Android Ver     10357 non-null  str
dtypes: datetime64[us](1), float64(3), str(9)
memory usage: 1.1 MB

In [62]:
uniq_installs = df['Installs'].unique()

In [63]:
replace_values = {}
for value in uniq_installs:
    replace_values.setdefault(value, value.replace(',', '').replace('+', ''))

In [64]:
df['Installs'] = df['Installs'].replace(replace_values).astype(int)

In [65]:
df.info()

<class 'pandas.DataFrame'>
Index: 10357 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10357 non-null  str
 1   Category        10357 non-null  str
 2   Rating          10357 non-null  float64
 3   Reviews         10357 non-null  float64
 4   Size            10357 non-null  str
 5   Installs        10357 non-null  int64
 6   Type            10357 non-null  str
 7   Price           10357 non-null  float64
 8   Content Rating  10357 non-null  str
 9   Genres          10357 non-null  str
 10  Last Updated    10357 non-null  datetime64[us]
 11  Current Ver     10357 non-null  str
 12  Android Ver     10357 non-null  str
dtypes: datetime64[us](1), float64(3), int64(1), str(8)
memory usage: 1.1 MB

In [66]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7M,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25M,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8M,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up

## Вывод по выполненной предобработке данных

В ходе работы был проведён этап очистки и подготовки датасета Google Play Store для дальнейшего анализа и использования в задачах машинного обучения.

На первом этапе был обнаружен и удалён некорректный выброс в данных (строка с индексом 10472), который нарушал структуру датасета. После этого была выполнена проверка размеров и структуры данных с помощью `shape` и `info()`.

Далее была обработана пропущенная информация. Для числового признака `Rating` пропуски были заполнены медианным значением, что позволило сохранить распределение данных без сильного влияния выбросов. Для категориальных признаков (`Type`, `Content Rating`, `Current Ver`, `Android Ver`) пропущенные значения были заменены на наиболее логичные константы, отражающие типичные значения в этих столбцах.

После этого были удалены дубликаты строк, что позволило избежать искажения статистики и переобучения моделей.

Числовой признак `Reviews` был приведён к типу `float`, а столбец `Last Updated` преобразован в формат datetime для дальнейшей работы с временными признаками.

Также был выполнен этап очистки признака `Installs`: удалены лишние символы (запятые и знак "+"), после чего данные были приведены к числовому типу `int`.

В результате датасет был приведён к корректному и согласованному виду, пригодному для дальнейшего анализа, визуализации и построения моделей машинного обучения.

## Задачи для классификации:
- Предсказать, является ли приложение Free / Paid (target: `Type`)
- Предсказать категорию приложения Game, Education, Tools и т.д. (target: `Category`)
- Предсказать уровень контента (target: `Content Rating`)

In [111]:
df.shape

(10357, 13)

In [112]:
df['Type'].value_counts()

Type
Free    9592
Paid     765
Name: count, dtype: int64

In [113]:
X = df.drop('Type', axis=1)
X['Last Updated Year'] = X['Last Updated'].dt.year
X['Last Updated Month'] = X['Last Updated'].dt.month
X['Last Updated day'] = X['Last Updated'].dt.day
X = X.drop('Last Updated', axis=1)
X = X.drop('Price', axis=1)

In [114]:
le = LabelEncoder()
y = le.fit_transform(df['Type'])
print(le.classes_)

['Free' 'Paid']

In [115]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=.2,
    random_state=42, 
    stratify=y
)

In [116]:
num_cols = X_train.select_dtypes(include=['int64', 'float64']).columns
cat_cols = X_train.select_dtypes(include=['string']).columns

In [117]:
preprocessor_num = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ]
)

preprocessor_tree = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', num_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ]
)

In [118]:
pipe = make_pipeline(
    preprocessor_tree,
    DecisionTreeClassifier(random_state=42)
)

In [119]:
pipe.get_params().keys()

dict_keys(['memory', 'steps', 'transform_input', 'verbose', 'columntransformer', 'decisiontreeclassifier', 'columntransformer__n_jobs', 'columntransformer__remainder', 'columntransformer__sparse_threshold', 'columntransformer__transformer_weights', 'columntransformer__transformers', 'columntransformer__verbose', 'columntransformer__verbose_feature_names_out', 'columntransformer__num', 'columntransformer__cat', 'columntransformer__cat__categories', 'columntransformer__cat__drop', 'columntransformer__cat__dtype', 'columntransformer__cat__feature_name_combiner', 'columntransformer__cat__handle_unknown', 'columntransformer__cat__max_categories', 'columntransformer__cat__min_frequency', 'columntransformer__cat__sparse_output', 'decisiontreeclassifier__ccp_alpha', 'decisiontreeclassifier__class_weight', 'decisiontreeclassifier__criterion', 'decisiontreeclassifier__max_depth', 'decisiontreeclassifier__max_features', 'decisiontreeclassifier__max_leaf_nodes', 'decisiontreeclassifier__min_impurity_decrease', 'decisiontreeclassifier__min_samples_leaf', 'decisiontreeclassifier__min_samples_split', 'decisiontreeclassifier__min_weight_fraction_leaf', 'decisiontreeclassifier__monotonic_cst', 'decisiontreeclassifier__random_state', 'decisiontreeclassifier__splitter'])

In [120]:
param_grid = {
    'decisiontreeclassifier__criterion': [
        'gini',
        'entropy',
        'log_loss'
    ],

    'decisiontreeclassifier__max_depth': [
        3, 5, 10, 15, 20, None
    ],

    'decisiontreeclassifier__min_samples_split': [
        2, 5, 10, 20
    ],

    'decisiontreeclassifier__min_samples_leaf': [
        1, 2, 5, 10
    ]
}

In [121]:
grid = GridSearchCV(
    estimator=pipe,
    param_grid=param_grid,
    scoring='f1',
    cv=5,
    n_jobs=-1,
    verbose=2
)

In [122]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 288 candidates, totalling 1440 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('num',
                                                                         'passthrough',
                                                                         Index(['Rating', 'Reviews', 'Installs'], dtype='str')),
                                                                        ('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         Index(['App', 'Category', 'Size', 'Content Rating', 'Genres', 'Current Ver',
       'Android Ver'],
      dtype='str'))])),
                                       ('decisiontreeclassifier',
                                        DecisionTreeClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'decisiontreeclassifier__criterion': ['gini',
                                                               'entropy',
                                                               'log_loss'],
                         'decisiontreeclassifier__max_depth': [3, 5, 10, 15, 20,
                                                               None],
                         'decisiontreeclassifier__min_samples_leaf': [1, 2, 5,
                                                                      10],
                         'decisiontreeclassifier__min_samples_split': [2, 5, 10,
                                                                       20]},
             scoring='f1', verbose=2)

In [123]:
print(grid.best_params_)
print(grid.best_score_)

{'decisiontreeclassifier__criterion': 'gini', 'decisiontreeclassifier__max_depth': None, 'decisiontreeclassifier__min_samples_leaf': 1, 'decisiontreeclassifier__min_samples_split': 2}
0.4636899914817317

In [124]:
y_pred = grid.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.98      0.96      1919
           1       0.53      0.33      0.41       153

    accuracy                           0.93      2072
   macro avg       0.74      0.65      0.69      2072
weighted avg       0.92      0.93      0.92      2072