In [21]:
import pandas as pd

# Работа с Pandas

Загрузите ваш DataFrame в переменную df и выведете на экран первые пять строк

In [22]:
df = pd.read_csv('googleplaystore.csv') # ваш путь к файлу с данными
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

Отобразите количество строк и столбцов в DataFrame

In [23]:
df.shape

(10841, 13)

# PRO часть (Не обязательна к выполнению, но желательна :))

Измените названия всех столбцов приведя их к нижнему регистру

In [28]:
column_names = list(df.columns)

lower_column_names = []

for word in column_names:
    lower_column_names.append(word.lower())
    
df.columns = lower_column_names

Выведите основные статистики по категориальным столбцам. Напишите выводы о них

In [42]:
df.describe(include='object')

,app,category,reviews,size,installs,type,content rating,genres,last updated,current ver,android ver
count,10841,10841,10841,10841,10841,10840,10840,10841,10841,10833,10838
unique,9660,34,6002,462,22,3,6,120,1378,2832,33
top,ROBLOX,FAMILY,0,Varies with device,"1,000,000+",Free,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,596,1695,1579,10039,8714,842,326,1459,2451

count - число элементов<br>
unique - число уникальных элементов<br>
top - какой элемент встречался чаще всего<br>
freq - сколько раз встречался этот элемент<br>

Выведите на экран часть датафрейма, который соответствует условию: `приложение из категории искусства и дизайна` И `с рейтингом больше 4.5`

In [43]:
df.loc[(df['category'] == 'ART_AND_DESIGN') & (df['rating'] > 4.5)]

,app,category,rating,reviews,size,installs,type,price,content rating,genres,last updated,current ver,android ver
1656,Solitaire,GAME,4.7,254258,23M,"10,000,000+",Free,0.00,Everyone,Card,"August 1, 2018",2.137.0,4.1 and up
1660,Clash Royale,GAME,4.6,23133508,97M,"100,000,000+",Free,0.00,Everyone 10+,Strategy,"June 27, 2018",2.3.2,4.1 and up
1664,Block Puzzle,GAME,4.6,59800,7.8M,"5,000,000+",Free,0.00,Everyone,Puzzle,"March 6, 2018",2.9,2.3 and up
1670,Clash of Clans,GAME,4.6,44891723,98M,"100,000,000+",Free,0.00,Everyone 10+,Strategy,"July 15, 2018",10.322.16,4.1 and up
1677,Bubble Witch 3 Saga,GAME,4.7,1732263,78M,"50,000,000+",Free,0.00,Everyone,Puzzle,"July 17, 2018",4.8.4,3.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10484,"FJ Final Join , Circles Game",GAME,4.7,32,24M,"1,000+",Free,0.00,Teen,Arcade,"July 11, 2018",0.24,4.3 and up
10679,Solitaire+,GAME,4.6,11235,Varies with device,"100,000+",Paid,2.99,Everyone,Card,"July 30, 2018",Varies with device,Varies with device
10697,Mu.F.O.,GAME,5.0,2,16M,1+,Paid,0.99,Everyone,Arcade,"March 3, 2017",1.0,2.3 and up
10721,Mad Dash Fo' Cash,GAME,5.0,14,16M,100+,Free,0.00,Everyone,Arcade,"June 19, 2017",2.5a,4.1 and up
10776,Monster Ride Pro,GAME,5.0,1,24M,10+,Free,0.00,Everyone,Racing,"March 5, 2018",2.0,2.3 and up

Посчитатайте какое количество игр содержится в рейтинге, используя параметр разбиения (bins) равным 100. Выведите на экран топ-10 игр по количеству в рейтинге. Напишите краткий вывод.
То есть сначала отфильтровываете лишь игры из всего датафрейма, после чего применяете value_counts к столбцу с рейтингом используя параметр, который указан выше. И выводите первые 10 строк отсортированных по убыванию.

In [52]:
# Фильтруем только игры 
game_df = df[df['category'] == 'GAME']

# Используем метод value_counts для подсчета количества игр в каждом рейтинге
rating_counts = game_df['rating'].value_counts(bins=100)
print('Количество игр в каждом рейтинге: ' + str(rating_counts))

print('===================================================================================')

# Выводим топ-10 игр по количеству в рейтинге
top_10_games = game_df.sort_values(by='rating', ascending=False).head(10)
print(top_10_games[['app', 'rating']])

Количество игр в каждом рейтинге: rating
(4.48, 4.52]    174
(4.36, 4.4]     166
(4.28, 4.32]    151
(4.56, 4.6]     121
(4.16, 4.2]     115
               ...
(3.04, 3.08]      0
(1.04, 1.08]      0
(1.84, 1.88]      0
(2.92, 2.96]      0
(3.0, 3.04]       0
Name: count, Length: 100, dtype: int64
===================================================================================
                                               app  rating
7698                                     CP Trivia     5.0
5917                                      Ra Ga Ba     5.0
9056                   Santa's Monster Shootout DX     5.0
5795                              Axe Champs! Wars     5.0
6700                              Brick Breaker BR     5.0
7466                                        211:CK     5.0
5822   Flippy Axe : Flip The Knife & Axe Simulator     5.0
9265                                      EC Mover     5.0
7402                          Trovami se ci riesci     5.0
10721                            Mad Dash Fo' Cash     5.0

<b>Выводы:</b><br>
Наибольшее количество игр расположено в интервале с рейтингом около 4.5.<br>
Игр с низким рейтингом нет.

Создайте функцию , которая будет применена к столбцу рейтинг методом `apply()`.
Функция должна принимать строку с рейтингом и возвращать:
 - High rating, если рейтинг больше или равен 4.5
 - Middle rating, если рейтинг между 3.8 и 4.5
 - Low rating, если рейтинг меньше 3.8 
Результат работы функции запишите в новый столбец с названием `categorical_rating`

In [54]:
def check_rating(rating: str) -> str:
    if rating >= 4.5:
        return 'High rating'
    elif rating >= 3.8 and rating < 4.5:
        return 'Middle rating'
    else:
        return 'Low rating'
    
df['rating'].apply(check_rating)

0        Middle rating
1        Middle rating
2          High rating
3          High rating
4        Middle rating
             ...
10836      High rating
10837      High rating
10838       Low rating
10839      High rating
10840      High rating
Name: rating, Length: 10841, dtype: object

Выведите кол-во уникальных значений в столбцах отсортированных по убыванию на экран:

In [55]:
df.nunique().sort_values(ascending=False)

app               9660
reviews           6002
current ver       2832
last updated      1378
size               462
genres             120
price               92
rating              40
category            34
android ver         33
installs            22
content rating       6
type                 3
dtype: int64

__Super-Hard задания__

Решите задачу, где мы создавали свою собственную функцию, но вместо функции `def` используйте `лямбда-функцию` внутри `apply()`

In [56]:
df['rating'].apply(lambda x : 'High rating' if x >= 4.5 else ('Middle rating' if x >= 3.8 and x < 4.5 else 'Low rating'))

0        Middle rating
1        Middle rating
2          High rating
3          High rating
4        Middle rating
             ...
10836      High rating
10837      High rating
10838       Low rating
10839      High rating
10840      High rating
Name: rating, Length: 10841, dtype: object

Изучите функцию `transform` в документации Pandas. Примените её к датафрейму, который будет заранее сгруппирован по столбцу `category`. С помощью фукнции `transform` найдите средний `rating` по каждой категории и запишите в столбец с названием `mean_cat_rating`. Кол-во строк в получившемся новом столбец должно быть таким же, как и в исходном датафрейме

In [57]:
df['mean_cat_reting'] = df.groupby('category')['rating'].transform('mean')
df

,app,category,rating,reviews,size,installs,type,price,content rating,genres,last updated,current ver,android ver,mean_cat_reting
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,4.358065
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,4.358065
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,4.358065
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,4.358065
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,4.358065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,4.192272
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,4.192272
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0.0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,4.189143
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0.0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,4.346067
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,4.094904

Создайте функцию , которая будет применена к столбцу `last updated` и возвращать из него число месяца, если число месяца вернуть из строки невозможно, то верните вместо этого строку с значением `miss_date`.\
Запишите полученный столбец в датафрейм , название столбцу дайте `day_of_update`.

Если вы столкнётесь с некоторой ошибкой , которую вам выдаст Pandas, то изучите конструкцию Python `try` \ `except`.\
Вот псевдокод , который поможет лучше разобраться с этой конструкцией:

In [60]:
import re

def number_of_month(date: str) -> str:
    try: # Помещаете то, что должно выполниться внутрь try, если же внутри try появляется ошибка, то условие переключается на оператор except и выполняется всё то, что находится внутри except.
        number = re.search(r'\b\d+\b', date)
        return number[0]
    except:
        return 'miss_date'

df['date_of_update'] = df['last updated'].apply(number_of_month)
df

,app,category,rating,reviews,size,installs,type,price,content rating,genres,last updated,current ver,android ver,mean_cat_reting,date_of_update
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,4.358065,7
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,4.358065,15
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,4.358065,1
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,4.358065,8
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,4.358065,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,4.192272,25
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,4.192272,6
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0.0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,4.189143,20
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0.0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,4.346067,19
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,4.094904,25